// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=cellar/design
// --out=$(GOPATH)/src/cellar
// --version=v1.3.1

package app
